//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Afwijking { get; set; }
        public Nullable<bool> leeftijd { get; set; }
        public Nullable<int> duur { get; set; }
        public Nullable<int> ruis_gehalte { get; set; }
        public string location { get; set; }
    }
}
